// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbxqyupt_CYBQLIoArfslYVMqAlMGvJeE',
    appId: '1:320347320931:web:9c5c23e47e3f65d52b3e56',
    messagingSenderId: '320347320931',
    projectId: 'booking-app-5705b',
    authDomain: 'booking-app-5705b.firebaseapp.com',
    storageBucket: 'booking-app-5705b.firebasestorage.app',
    measurementId: 'G-D9TXYESK4D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCd2OyUgGHQAlHATn1S7KW-Alad-SpzAvg',
    appId: '1:320347320931:android:1db95bb7d849d5d52b3e56',
    messagingSenderId: '320347320931',
    projectId: 'booking-app-5705b',
    storageBucket: 'booking-app-5705b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7LmoUj62Kpj7c7U97l7Ewi4JHKdjjR6w',
    appId: '1:320347320931:ios:7c935016c0633fb62b3e56',
    messagingSenderId: '320347320931',
    projectId: 'booking-app-5705b',
    storageBucket: 'booking-app-5705b.firebasestorage.app',
    iosBundleId: 'com.example.hotelBooking',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7LmoUj62Kpj7c7U97l7Ewi4JHKdjjR6w',
    appId: '1:320347320931:ios:7c935016c0633fb62b3e56',
    messagingSenderId: '320347320931',
    projectId: 'booking-app-5705b',
    storageBucket: 'booking-app-5705b.firebasestorage.app',
    iosBundleId: 'com.example.hotelBooking',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCbxqyupt_CYBQLIoArfslYVMqAlMGvJeE',
    appId: '1:320347320931:web:d7b3be94657c59842b3e56',
    messagingSenderId: '320347320931',
    projectId: 'booking-app-5705b',
    authDomain: 'booking-app-5705b.firebaseapp.com',
    storageBucket: 'booking-app-5705b.firebasestorage.app',
    measurementId: 'G-YBFWDFX8HZ',
  );
}
